services:
  backend:
    image: ghcr.io/malaneph/gym-tracker:latest
    ports:
      - "8005:8005"
    command: [ "php", "artisan", "octane:start", "--server=frankenphp", "--port=8005" ]
    restart: unless-stopped
    env_file:
      - path: .env
    networks:
      - gym-tracker-network

networks:
  gym-tracker-network:
    name: gym-tracker-network
    driver: bridge
