services:
  backend:
    image: serversideup/php:8.5-frankenphp
    ports:
      - "8005:8005"
    volumes:
      - .:/var/www/html
    command: [ "php", "artisan", "octane:start", "--server=frankenphp", "--port=8005" ]
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "healthcheck-octane" ]
      start_period: 10s
    restart: unless-stopped
